### ISSUE TITLE
Update from Raven to new Sentry SDK

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-versionista-scraper#162]
At some point in the last few months, Sentry deprecated all their “Raven” SDKs and switched to a whole new series of “Sentry SDKs.” (Not sure how I missed this, but I really feel like there wasn’t any major, clear notice.) We should update, since docs for old Raven SDK are now hard to find, increasing the likelihood we misconfigure something.

**Comment by Mr0grog** [comment]
Gah, I can’t believe I never got this done! This is only getting more important as the old SDK gets more and more out of date.

**Comment by c3ho** [comment]
Hi, I'm a first time contributor and want to work on this issue. Is it possible to work on this issue?

**Comment by Mr0grog** [comment]
@c3ho Absolutely, go ahead!

**Comment by c3ho** [comment]
Thanks!

I installed the new SDK, however I think there might be a few things we need to look at.

In the legacy:
![image](https://user-images.githubusercontent.com/18711727/66246421-deb5d780-e6e1-11e9-9bf1-6364d70bc2f3.png)

This is the new configuration method:
![image](https://user-images.githubusercontent.com/18711727/66246434-fe4d0000-e6e1-11e9-92a2-25bb5a588500.png)

Right now in the sentry-error.js file const Raven, the variable is also exported for use. Did you want to use the Raven variable for now and change it in another PR?

Do you have any tips on how I would test the changes to make sure the current changes are not breaking anything?

**Comment by Mr0grog** [comment]
> Right now in the sentry-error.js file const Raven, the variable is also exported for use. Did you want to use the Raven variable for now and change it in another PR?

It’s not actually used, so you should just change it now.

> the following is what I have for the new one

That works fine, but it might be nicer to just have the signature be `setup(options)` now. I’m not super concerned about it, either way.

> I tried following the instructions in the readme, however I keep getting a web page that looks like this

Where do you wind up with a web page? The `scrape-versionista` script is a CLI tool that generates JSON or CSV files.

**Comment by c3ho** [comment]
>Right now in the sentry-error.js file const Raven, the variable is also exported for use. Did you want to use the Raven variable for now and change it in another PR?

>It’s not actually used, so you should just change it now.

Got it, changed all that

>That works fine, but it might be nicer to just have the signature be setup(options) now. I’m not super concerned about it, either way.

You mean to
```
exports.setup = function (options){
  Sentry.init(Object.assign({}, defaultOptions, options});
  return exports;
}
```
I was under the impression from the documentation a dsn is required for init.

Sorry, that was my mistake, I followed the process and made an account on versionista(with a site to follow) as well as sentry(to get a dsn)

I still do get an error though, no csv, but an email with the same issue I got from CLI

**Comment by Mr0grog** [comment]
> I was under the impression from the documentation a dsn is required for init.

If it’s not provided, it’ll read it from the `SENTRY_DSN` environment variable (which is how we use it), and if that’s not set, everything is fine, but it makes any Sentry method calls into no-ops (which is super useful, because you don’t have to guard your Sentry calls with things like `if (isDevMode) { sentry.captureMessage(...); }`).

> I still do get an error though, no csv, but an email with the same issue I got from CLI

You’ll need to rebase on the master branch to get the fix that was in #244.

**Comment by c3ho** [comment]
Thank you, that fixed everything!

**Comment by c3ho** [comment]
Here's the PR for the issue #245
