### ISSUE TITLE
Diff Length Matches Text Diff Length

### ISSUE THREAD

**Issue by jjudish** [edgi-govdata-archiving/web-monitoring-versionista-scraper#222]
Hello,

When running the versionista scraper this past week, the output was different than normal: the "Diff Length" field matched the "Text Diff Length" field for every entry created by the scraper, which has never been the case before.  The analysts for the Web Integrity project use the text diff length to determine whether or not to closely examine a page, so the change this past week led to some confusion.  Are the matching diff fields to be expected in the future or is it possible to fix this change?

Thanks in advance for any help!

**Comment by jjudish** [comment]
I take it back, it seems to have been a versionista glitch last week. The Diff Lengths were different again this week.  Thanks!

**Comment by Mr0grog** [comment]
Ah! Good to know. Sorry I didn’t get on this earlier, but good to know it was just a transient issue.

**Comment by jjudish** [comment]
Hi again!
Unfortunately the issue isn't as transient as I thought it was.  The issue has persisted for the past couple weeks.  The error seems to occur semi-randomly, as in the past few weeks simply rerunning the scrape program has sometimes resolved the issue of the text hash length matching the diff hash length.

The actual script I am running is bin/scrape-versionista-and-email.  I have attached an example spreadsheet where the text and diff lengths match for every entry.  Any help figuring out why this occurs would be greatly appreciated.  Thanks in advance for any help!

[HHS - CDC - cdc.gov_nchs - Health Statistics_2019-06-08T17_41_40.082Z.xlsx](https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/files/3374340/HHS.-.CDC.-.cdc.gov_nchs.-.Health.Statistics_2019-06-08T17_41_40.082Z.xlsx)

**Comment by Mr0grog** [comment]
Hmmmm, it’s possible that output is accurate, but you’re right, it definitely looks wrong. We recently stopped all our Versionista operations, so I don’t have a working account to test with, and I am also traveling for the rest of July, so it may take me some time to get to the bottom of it.

I don’t think 6e7eadd38b340ba6989d71f13cef7fff970fa626 would be related — that script doesn’t get used by the one you’re running, and actually doesn’t really relate to Versionista at all! (It’s a bit of a historical mistake that it’s in this repo.)

In the mean time, could you try adding `--save-diffs` to the list of arguments here? https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/blob/4461528e8437d4ea7d193cfb43c5bd1903809592/bin/scrape-versionista-and-email#L81-L97

That should cause it to include the actual diff output in the resulting file, so you can compare the actual data to the lengths and hashes you’re seeing.

---

More thoughts:

The function that gets the data for the diff hashes and lengths is here: https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/blob/4461528e8437d4ea7d193cfb43c5bd1903809592/bin/scrape-versionista#L235-L292

…which uses `Versionista.getVersionDiff()` here: https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/blob/4461528e8437d4ea7d193cfb43c5bd1903809592/lib/versionista.js#L697-L783

I’m not seeing anything obvious that would get us into situations where the text diff and normal diff’s lengths would get mixed up.

**Comment by Mr0grog** [comment]
FWIW, I think the data is probably either correct or the error is on our side, not Versionista’s, since we calculate both the length and hash, rather than retrieving them separately from Versionista.

**Comment by Mr0grog** [comment]
OK, I have a new test account that's been gathering data for a few days, but I can’t seem to reproduce what you’re seeing.

How intermittent is it? Do you have the same issues if you immediately run a new job for the same timeframe?

If you want, we could figure out a way for you to send me credentials for you account to test on.

**Comment by jjudish** [comment]
Hi Mr0grog,

Thanks for responding.  The issue happens every time I run the scrape now.  Fortunately, I've been looking into the problem and think I have found the issue.  I believe it occurs at

https://github.com/edgi-govdata-archiving/web-monitoring-versionista-scraper/blob/4461528e8437d4ea7d193cfb43c5bd1903809592/lib/versionista.js#L734

It seems that in my case versionista was appending the string `?showscript` to the end of the url when loading a page, so when the program appended the diffType to the end of actualUri.path, the url would look like:
`v-cache.com/pa/iIxpl4KPRgRoS6REsQQ_wBlUVCRpluh9yhZh7Bbm45pADI1iP4hMyPkZf1IKclww/?showscripttext_only`
instead of:
 `v-cache.com/pa/iIxpl4KPRgRoS6REsQQ_wBlUVCRpluh9yhZh7Bbm45pADI1iP4hMyPkZf1IKclww/text_only`

I seem to have fixed the issue by replacing line 734 with:
```
var newUrl = `${diffHost}/api/ip_url${actualUri.path}${diffType}`;
var showscriptIndex = newUrl.indexOf("?showscript")
if(showscriptIndex != -1){
	newUrl = newUrl.substr(0, showscriptIndex);
	newUrl = newUrl + diffType;
}
return newUrl;
```
I'm not that familiar with javascript so there is probably a cleaner way to sanitize the url path than this but it seems to work so far.  I'm also not 100% sure yet if this is the cause of the matching hashes, but so far the bugs seem to be fixed in preliminary testing.

Thanks for continuing to look into the issue!  If EDGI is transitioning from using Versionista is there a different technology or method that you would recommend we switch to?  I don't do much software development so if Versionista has another change in the future it would be helpful to be aware of other alternatives than trying to figure out how to maintain support for Versionista.

Thanks again for all the help

**Comment by Mr0grog** [comment]
Ahhhhhhhhhhhhh! OK, we can do this slightly better, because what we really want to do is parse the URL and insert `diffType` right before the querystring. I think I can whip up something real quick for this.

**Comment by Mr0grog** [comment]
Alright, that info also helped me reliably reproduce the problem :)

@jjudish, would you mind checking out the code in the `222-querystrings-in-diff-urls-are-a-thing-actually` (that’s PR #225) and seeing if it also works for you? It’s a slightly cleaned up version of your fix.

**Comment by Mr0grog** [comment]
> Is there a different technology or method that you would recommend we switch to?

We’ve built up a good partnership with the Internet Archive, and are poking around at some other internal tools, too. Are you on the [Archives Slack](https://archivers.slack.com/)? (You can self-sign-up at https://archivers-slack.herokuapp.com/) I’d be happy to chat there or do a video call walking you through things—in fact, we were talking a bit at EDGI about how to WIP onto a more similar workflow as ours. (Only assuming you’d want to be!)

**Comment by jjudish** [comment]
The fix works perfectly and is far cleaner than the code I wrote, thanks a bunch!

I'll check with the director of WIP; if she feels that it would be wise to switch workflows then I'd be happy to chat with you about updating it.

Thanks again for all the help!
