### ISSUE TITLE
Add a column with links to the UI

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-versionista-scraper#58]
Each row is a Change and should link to the corresponding Change view in the UI.

I think we decided that we should leave the Versionista links in the Google Sheet for now, too, but move them off to the right so that the UI link is the "default" one. To recap our discussion: analysts can get to the Versionista view via the app, of course, but if the app is consistently failing it will be convenient for them to be able to go directly from the Sheet.

**Comment by Mr0grog** [comment]
@trinberg what’s the right place to put in our links right now?

- Most aggressive would be to simply replace all the Versionista links (“Page View URL,” “Last Two - Side by Side,” and “Latest to Base - Side by Side”) with ours.

- Moderate would probably be a subset of those

- Really minimal might be to swap out the “Unique ID” column for a link to our UI. I’d prefer not to do that because I think people will miss it, but it *is* low impact.

**Comment by Mr0grog** [comment]
I should note here that I’m assuming it’s not feasible to add new columns, since all the sheets with extra columns for analysts to fill in would need to be shifted around.

**Comment by trinberg** [comment]
Reposting my message from Slack:

> Ok, so my thought here is that it would actually be good to keep both the versionista and EDGI software links (latest to base and last two) available to the analysts on one sheet. Switching sheets would be quite annoying for anyone who would like to make a comparison between versionista and the new software. And I think we want to keep the two workflows available in parallel during this transition.
> 
> So my suggestion would actually be for me and @rayc to go through and make sure +2 more columns get added to all the corresponding sheets. We should make sure to get this right, so I think holding off till next round is a good idea. 
> 
> What do other folks think? This may be a bit of work to set up, but hopefully makes it a more robust transition (esp. if if we have to deal with downtime or errors with the new software)

**Comment by trinberg** [comment]
Would be good to get others on the team to weigh in, as maybe people will be opposed, so I'll follow up once we make a decision on this.

**Comment by Mr0grog** [comment]
#58 does what we talked about in the meeting (changing two of the three link columns), but we can *really* easily change that to adding new columns instead. Sounds like there’s definitely continued discussion needed.

**Comment by weatherpattern** [comment]
Based on the 1/3 meeting, @Mr0grog will produce two sets of sheets. One with 3 versionaista links and other changing Last to Bast, and Last Two to our UI, and the Page URL will point to versionista.
