### ISSUE TITLE
Add support for Sentry releases

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-versionista-scraper#77]
We should add support for posting release info to Sentry from CI when we merge to master so we can automatically connect reports in Sentry to PRs and commits. See the docs: https://docs.sentry.io/learn/releases/

**Comment by lightandluck** [comment]
Reopening because this was commented on

**Comment by Mr0grog** [comment]
Closing this since we aren’t actively doing a whole lot of work with Versionista anymore. Can reopen if something changes.
